apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: dropmong-rate-limit-payments
config:
  minute: 1000000
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: dropmong-rate-limit-notifications
config:
  minute: 1000000
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: dropmong-rate-limit-orders
config:
  minute: 1000000
  policy: local
