apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - manifests/namespace.yaml
  - manifests/grafana-ingress.yaml
  - manifests/istio-mesh-podmonitors.yaml
  - manifests/prometheusrules/service-slo-alerts.yaml
  - manifests/prometheusrules/system-kubernetes-alerts.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: grafana-dashboard
    app.kubernetes.io/part-of: dropmong-platform
    grafana_dashboard: "1"
configMapGenerator:
  - name: dropmong-ops-dashboards
    options:
      annotations:
        k8s-sidecar-target-directory: Ops
    files:
      - dashboards/ops/00-service-overview.json
      - dashboards/ops/10-runtime-and-telemetry.json
  - name: dropmong-logs-dashboards
    options:
      annotations:
        k8s-sidecar-target-directory: Logs
    files:
      - dashboards/logs/10-request-investigation.json
      - dashboards/logs/20-service-errors.json
      - dashboards/logs/30-kafka-correlation.json
  - name: dropmong-db-dashboards
    options:
      annotations:
        k8s-sidecar-target-directory: DB
    files:
      - dashboards/db/10-postgresql-overview.json
      - dashboards/db/20-db-trace-correlation.json
  - name: dropmong-load-dashboards
    options:
      annotations:
        k8s-sidecar-target-directory: Load
    files:
      - dashboards/load/10-api-load-overview.json
      - dashboards/load/20-slow-request-traces.json
