apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medikong-istio-workload-security-private-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/Medikong/e-gitops.git
    targetRevision: HEAD
    path: platform/istio/private-dev/workload-security
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - SkipDryRunOnMissingResource=true
