apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-auth
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-coupon
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-backoffice
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-payment
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-notification
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-web
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-order
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-interest
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-messaging
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: synthetic
  labels:
    app.kubernetes.io/part-of: medikong
