apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-auth
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-coupon
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-payment
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-notification
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-web
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-order
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-interest
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-user
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-catalog
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-system
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-messaging
  labels:
    app.kubernetes.io/part-of: medikong
