apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-virtualservice.yaml
  - catalog-virtualservice.yaml
  - order-virtualservice.yaml
  - payment-virtualservice.yaml
  - notification-virtualservice.yaml
  - ext-authz-policy.yaml
