apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interest-aws-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Medikong/e-gitops.git
      targetRevision: HEAD
      path: charts/medikong-service
      helm:
        releaseName: interest-aws-dev
        valueFiles:
          - $values/values/base.yaml
          - $values/values/env/aws-dev.yaml
          - $values/values/services/interest.yaml
          - $values/values/services/aws-dev/interest.yaml
          - $values/values/services/aws-dev/ingress-disabled.yaml
    - repoURL: https://github.com/Medikong/e-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dropmong-interest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
