apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    chaos-mesh.org/inject: enabled
  labels:
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: medikong-platform
