apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    chaos-mesh.org/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: dropmong-order
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    chaos-mesh.org/inject: enabled
