apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-store.yaml
  - grafana-admin-credentials.yaml
  - grafana-renderer-token.yaml
  - readiness-rbac.yaml
  - readiness-job.yaml
