apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      role: arn:aws:iam::205623789422:role/medikong-dev-external-secrets-grafana-role
