apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-controller-manager
  namespace: chaos-mesh
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-chaos-controller-manager-target-namespace
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - patch
      - create
      - watch
      - list
      - get
  - apiGroups:
      - chaos-mesh.org
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-chaos-controller-manager-cluster-level
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-mesh-chaos-controller-manager-control-plane
  namespace: chaos-mesh
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-chaos-controller-manager-cluster-level
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-mesh-chaos-controller-manager-cluster-level
subjects:
  - kind: ServiceAccount
    name: chaos-controller-manager
    namespace: chaos-mesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-mesh-chaos-controller-manager-control-plane
  namespace: chaos-mesh
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-mesh-chaos-controller-manager-control-plane
subjects:
  - kind: ServiceAccount
    name: chaos-controller-manager
    namespace: chaos-mesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-chaos-controller-manager-target-namespace
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: medikong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-mesh-chaos-controller-manager-target-namespace
subjects:
  - kind: ServiceAccount
    name: chaos-controller-manager
    namespace: chaos-mesh
