apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: payment-service-strict-mtls
  namespace: dropmong-payment
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: medikong
    medikong.io/security-scenario: mtls-strict-meshed-backends
spec:
  selector:
    matchLabels:
      app: payment-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: notification-service-strict-mtls
  namespace: dropmong-notification
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: medikong
    medikong.io/security-scenario: mtls-strict-meshed-backends
spec:
  selector:
    matchLabels:
      app: notification-service
  mtls:
    mode: STRICT
