apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-monitoring-config-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-34"
spec:
  project: default
  source:
    repoURL: https://github.com/Medikong/e-gitops.git
    targetRevision: HEAD
    path: platform/external-secrets/aws-dev/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
