apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medikong-istio-authz-rate-limit-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Medikong/e-gitops.git
    targetRevision: HEAD
    path: platform/istio/aws-dev/authz-rate-limit
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
